# Generated by Django 5.2.7 on 2025-10-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medex_app', '0002_orderitem_pharmacyreview_alter_stock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_images/'),
        ),
    ]
