# Generated by Django 5.2.7 on 2025-10-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medex_app', '0003_alter_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meds/'),
        ),
    ]
